#pragma once

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>
#include <cmath>
#include <glad/gl.h>

#include "app/XAppAdapter.h"
#include "app/XAppOptions.h"
#include "app/XApplication.h"
#include "app/XWindow.h"
#include "camera/XCamera.h"
#include "ecs/XComponent.h"
#include "ecs/XEntity.h"
#include "ecs/components/XMeshRendererComponent.h"
#include "ecs/components/XTransformComponent.h"
#include "graphics/XRenderer.h"
#include "graphics/geometry/XBoxGeometry.h"
#include "graphics/geometry/XGeometry.h"
#include "graphics/material/XMaterial.h"
#include "graphics/shaders/XProgram.h"
#include "graphics/shaders/XShader.h"
#include "graphics/textures/XImageData.h"
#include "graphics/textures/XTexture2D.h"
#include "graphics/textures/XTexture2DBuilder.h"
#include "io/XFileIO.h"
#include "io/ppm/XPPMReader.h"
#include "math/XMatrix4f.h"
#include "math/XVector4f.h"